### ISSUE TITLE
Add information about styling and style linter in README

### ISSUE THREAD

**Issue by sharmaadityaHQ** [sharmaaditya570191/bossy-helper#1]
We use `scss` for styling and `node-sass` module is required to use `sass` stylesheets. For linting `scss` we use `sass-lint` with our custom rules and configuration in `.sass-lint.yml`.

You can read more about it here: https://create-react-app.dev/docs/adding-a-sass-stylesheet

**Comment by RheaAdh** [comment]
can i take up this issue?

**Comment by RheaAdh** [comment]
#2  can u please check the pr and let me know if any changes
@sharmaaditya570191
