### ISSUE TITLE
Create home page for open source guide

### ISSUE THREAD

**Issue by sharmaadityaHQ** [sharmaaditya570191/bossy-helper#10]
![image](https://user-images.githubusercontent.com/42587159/87019495-50323180-c1f0-11ea-9225-44b7ad8082af.png)

This task includes to make a home page using the already available display component. You can take the images from here - https://opensource.guide/?ref=lapaninja

We are not going to make a clone of the same thing. Do not worry about the content. I will add it when you are ready with this page.

**Comment by kmrakash** [comment]
Hey I'm interested please assign
