### ISSUE TITLE
Improve scss styling and design

### ISSUE THREAD

**Issue by sharmaadityaHQ** [sharmaaditya570191/bossy-helper#13]
The current home page looks like this.  

![image](https://user-images.githubusercontent.com/42587159/87215301-f433ee00-c352-11ea-914e-590e2fc493aa.png)

Try improving the home page design. This can include better scss. Be creative, choose colors, try adding some animations on hovering over the cards.

**Comment by kmrakash** [comment]
Great . let me try something 
please assign me

**Comment by kmrakash** [comment]
![image](https://user-images.githubusercontent.com/47351616/87245610-3d279780-c464-11ea-9d87-3c59875bd94a.png)

Hey @sharmaaditya570191  does this look good in header part , the curve svg 
there is more like this shape . 
need your thought
