### ISSUE TITLE
Create React function component to display organization

### ISSUE THREAD

**Issue by sharmaadityaHQ** [sharmaaditya570191/bossy-helper#3]
![image](https://user-images.githubusercontent.com/42587159/85203192-a155b080-b329-11ea-9d24-174f560ee96b.png)

Create a React function component which accepts name of organization and a brief description as props and displays like the above card in the image.

Please ensure that you use `scss` for styling.

You can read more about React function components from here - https://reactjs.org/docs/components-and-props.html

**Comment by kmrakash** [comment]
i want to work on this issue please assign me
