### ISSUE TITLE
Create header component for home page

### ISSUE THREAD

**Issue by sharmaadityaHQ** [sharmaaditya570191/bossy-helper#5]
This is supposed to be an open source guide where we help people by showing them active open source projects of open source organizations along with their recent issues.

Please keep the above theme in mind when you design the react function component.

**Comment by kmrakash** [comment]
what should include a header component like , logo of bossy helper , organisation button  or anything else ??

**Comment by sharmaadityaHQ** [comment]
We can add the logo later. Think of a catchy phrase to display on top. It should make it clear that it is a guide to open source. Include some nice design or image alongside. Let me know if you want to work on it.

**Comment by kmrakash** [comment]
Yeah I'm interested ...
Just thinking what can be the good way.
